### ISSUE TITLE
Request to update builder-base Golang to 1.17.8

### ISSUE THREAD

**Issue by RedbackThomson** [aws/eks-distro-build-tooling#342] opened 2022-03-29 18:34 UTC
**What would you like to be added**:
Builder base currently uses [Golang 1.16.12](https://github.com/aws/eks-distro-build-tooling/blob/main/builder-base/versions.sh#L25). The AWS Controllers for K8s (ACK) project would love to use this image as our base for building our controllers, except we need at least 1.17. 

**Why is this needed**:
ACK needs 1.17 because we rely on that version for our latest go modules. We currently leverage the EKS-D nonroot image for our runtime images, but still need to use bitnami Golang 1.17 images for our builder until your image has been updated.

**Comment by TerryHowe** [comment] 2022-03-29 19:11
```
sh-4.3# find / -name go
/root/sdk/go1.17.5/pkg/linux_amd64/go
/root/sdk/go1.17.5/pkg/linux_amd64_race/go
/root/sdk/go1.17.5/misc/cgo/testcshared/testdata/go2c2go/go
/root/sdk/go1.17.5/bin/go
/root/sdk/go1.17.5/src/cmd/go
/root/sdk/go1.17.5/src/cmd/vendor/golang.org/x/tools/go
/root/sdk/go1.17.5/src/go
/root/sdk/go1.15.15/pkg/linux_amd64/go
/root/sdk/go1.15.15/pkg/linux_amd64_race/go
/root/sdk/go1.15.15/misc/cgo/testcshared/testdata/go2c2go/go
/root/sdk/go1.15.15/bin/go
/root/sdk/go1.15.15/src/cmd/go
/root/sdk/go1.15.15/src/cmd/vendor/golang.org/x/tools/go
/root/sdk/go1.15.15/src/go
/root/sdk/go1.14.15/pkg/linux_amd64/go
/root/sdk/go1.14.15/pkg/linux_amd64_race/go
/root/sdk/go1.14.15/misc/cgo/testcshared/testdata/go2c2go/go
/root/sdk/go1.14.15/bin/go
/root/sdk/go1.14.15/src/cmd/go
/root/sdk/go1.14.15/src/cmd/vendor/golang.org/x/tools/go
/root/sdk/go1.14.15/src/go
/root/sdk/go1.13.15/pkg/linux_amd64/go
/root/sdk/go1.13.15/pkg/linux_amd64_race/go
/root/sdk/go1.13.15/misc/cgo/testcshared/testdata/go2c2go/go
/root/sdk/go1.13.15/bin/go
/root/sdk/go1.13.15/src/cmd/go
/root/sdk/go1.13.15/src/cmd/vendor/golang.org/x/tools/go
/root/sdk/go1.13.15/src/go
/root/sdk/go1.16.12/pkg/linux_amd64/go
/root/sdk/go1.16.12/pkg/linux_amd64_race/go
/root/sdk/go1.16.12/misc/cgo/testcshared/testdata/go2c2go/go
/root/sdk/go1.16.12/bin/go
/root/sdk/go1.16.12/src/cmd/go
/root/sdk/go1.16.12/src/cmd/vendor/golang.org/x/tools/go
/root/sdk/go1.16.12/src/go
/usr/bin/go
/go
/go/go1.16/bin/go
/go/go1.17/bin/go
/go/go1.13/bin/go
/go/go1.14/bin/go
/go/go1.15/bin/go
sh-4.3# 
```

**Comment by abhay-krishna** [comment] 2022-03-29 20:15
@RedbackThomson You can use [these utility methods](https://github.com/aws/eks-distro/blob/main/build/lib/common.sh#L183-L231) to switch to any Go version you want from 1.13 to 1.17.

**Comment by RedbackThomson** [comment] 2022-03-29 20:43
@TerryHowe 

Hmmm that's good but only up to 1.17.5 sadly - 1.17.8 is the latest. 

@abhay-krishna 

Also good to know! I'll test this out in our image definition and get back to you!

**Comment by RedbackThomson** [comment] 2022-03-30 18:53
@abhay-krishna Yeah so I've been playing around with the builder base this morning but I see it only [installs 1.17.5](https://github.com/aws/eks-distro-build-tooling/blob/main/builder-base/install.sh#L188). So even if we do want to switch with that utility method, it's still not up-to-date enough. Can I create a PR to change this to 1.17.8? Can we unpin it from a patch version and just keep it at the latest version, so it's rebuild with the latest 1.17 every night?

**Comment by jaxesn** [comment] 2022-03-31 14:17
Yes, we would accept a PR to update to 1.17.8, if 1.16 is out of date, mind updating it too? 

On our side, our builds are all reproducible with checksums checked in for validation.  When we bump golang versions we need to roll these updates out through our various builds to get all the checksums updated without causing crazy havoc across our presubmits and what not.  I wouldn't be ready to unpin our patch version for now since we need to consider the downstream effects.  That said, we will pretty much be fine updating the versions whenever there are new versions, we just need to keep it as a specific decision.

**Comment by RedbackThomson** [comment] 2022-03-31 22:36
> I wouldn't be ready to unpin our patch version for now since we need to consider the downstream effects. That said, we will pretty much be fine updating the versions whenever there are new versions, we just need to keep it as a specific decision.

Okay. I can understand this concern, and the vetting process you'll need to consider before merging anything. Given you've not updated from 1.17.5 to 1.17.8 means that this hasn't been a worry for you in the 3 months between those releases. ACK is choosing to update to 1.17.8 because of the crypto package security concerns in the former version - as advice from both internal and external security auditors. Do you expect to also share those concerns? That is, do you foresee the EKS-D team actively updating the builder-base to maintain security standards for your generated binaries?

**Comment by jaxesn** [comment] 2022-04-01 16:54
Like I said though, we are fine to update whenever there are new versions, we just do not have a specific cadence we are currently following.  Your reasoning is as good as any to update.

**Comment by jaxesn** [comment] 2022-04-01 17:03
Ill open a PR to bump this.

**Comment by jaxesn** [comment] 2022-04-01 18:29
https://github.com/aws/eks-distro-build-tooling/pull/348

**Closed** 2022-04-01 19:17 UTC
